export const agents = [
  { id: 1, name: "Sarah Jenkins", avatar: "SJ", color: "#d4af37" },
  { id: 2, name: "Michael Chang", avatar: "MC", color: "#e5c158" },
  { id: 3, name: "Emily Rodriguez", avatar: "ER", color: "#f0d476" },
  { id: 4, name: "David Kim", avatar: "DK", color: "#c9a52a" },
];

export const listings = [
  // SALE LISTINGS (14)
  {
    id: 1,
    category: "Sale",
    title: "The Meridian",
    address: "42 Ocean View Drive, Bondi Beach NSW 2026",
    type: "Apartment",
    beds: 3,
    baths: 2,
    cars: 1,
    livingSize: 125,
    landSize: null,
    houseArea: 125,
    aspect: "North",
    price: 2350000,
    status: "Available",
    listedBy: "Sarah Jenkins",
    notes: "Stunning beachside apartment with panoramic ocean views. Floor-to-ceiling windows, premium finishes throughout.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/1aBcDeFgHiJkLmNoPqR" },
      { title: "Contract", url: "https://drive.google.com/drive/folders/1aBcDeFgHiJkLmNoPqR" },
    ],
    listingStyle: "Exclusive",
  },
  {
    id: 2,
    category: "Sale",
    title: "Harbour Heights",
    address: "18/300 George Street, Sydney NSW 2000",
    type: "Unit",
    beds: 2,
    baths: 2,
    cars: 1,
    livingSize: 98,
    landSize: null,
    houseArea: 98,
    aspect: "East",
    price: 1650000,
    status: "Available",
    listedBy: "Michael Chang",
    notes: "Luxury CBD apartment in the heart of the city. Walking distance to Circular Quay, restaurants and shops.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/2bCdEfGhIjKlMnOpQrS" },
    ],
    listingStyle: "Off-Market",
  },
  {
    id: 3,
    category: "Sale",
    title: "Federation Estate",
    address: "7 Rathmore Avenue, Mosman NSW 2088",
    type: "House",
    beds: 5,
    baths: 3,
    cars: 2,
    livingSize: 280,
    landSize: 650,
    houseArea: 280,
    aspect: "North",
    price: 3300000,
    status: "Hold",
    listedBy: "Emily Rodriguez",
    notes: "Grand federation home on prestige street. Manicured gardens, heated pool, self-contained guest cottage.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/3cDeFgHiJkLmNoPqRsT" },
      { title: "Contract", url: "https://drive.google.com/drive/folders/3cDeFgHiJkLmNoPqRsT" },
      { title: "Authority", url: "https://drive.google.com/drive/folders/3cDeFgHiJkLmNoPqRsT" },
    ],
    listingStyle: "Exclusive",
  },
  {
    id: 4,
    category: "Sale",
    title: "Surrey Hills Residence",
    address: "25 Victoria Road, Surrey Hills VIC 3127",
    type: "House",
    beds: 4,
    baths: 2,
    cars: 2,
    livingSize: 220,
    landSize: 580,
    houseArea: 220,
    aspect: "North",
    price: 2850000,
    status: "Available",
    listedBy: "David Kim",
    notes: "Renovated Victorian with period details. Open-plan living, north-facing backyard, walk to Surrey Hills station.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/4dEfGhIjKlMnOpQrStU" },
    ],
    listingStyle: "Exclusive",
  },
  {
    id: 5,
    category: "Sale",
    title: "The Quarters",
    address: "Unit 12, 88 Pitt Street, Parramatta NSW 2150",
    type: "Apartment",
    beds: 2,
    baths: 2,
    cars: 1,
    livingSize: 85,
    landSize: null,
    houseArea: 85,
    aspect: "West",
    price: 785000,
    status: "Available",
    listedBy: "Sarah Jenkins",
    notes: "Modern apartment in Parramatta's CBD. Secure parking, rooftop communal area, close to transport.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/5eFgHiJkLmNoPqRsTuV" },
      { title: "Contract", url: "https://drive.google.com/drive/folders/5eFgHiJkLmNoPqRsTuV" },
    ],
    listingStyle: "Off-Market",
  },
  {
    id: 6,
    category: "Sale",
    title: "Coogee Bay Villa",
    address: "9 Arden Street, Coogee NSW 2031",
    type: "House",
    beds: 4,
    baths: 3,
    cars: 2,
    livingSize: 195,
    landSize: 420,
    houseArea: 195,
    aspect: "East",
    price: 2950000,
    status: "Available",
    listedBy: "Michael Chang",
    notes: "Contemporary coastal home, 400m to Coogee Beach. Designer kitchen, stone benchtops, double glazing.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/6fGhIjKlMnOpQrStUvW" },
    ],
    listingStyle: "Exclusive",
  },
  {
    id: 7,
    category: "Sale",
    title: "Northcote Loft",
    address: "3/210 High Street, Northcote VIC 3070",
    type: "Apartment",
    beds: 1,
    baths: 1,
    cars: 1,
    livingSize: 62,
    landSize: null,
    houseArea: 62,
    aspect: "North",
    price: 750000,
    status: "Sold",
    listedBy: "Emily Rodriguez",
    notes: "Converted warehouse loft with soaring ceilings. Exposed brick, polished concrete floors, north light.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/7gHiJkLmNoPqRsTuvWx" },
    ],
    listingStyle: "Off-Market",
  },
  {
    id: 8,
    category: "Sale",
    title: "Toorak Manor",
    address: "14 Grange Road, Toorak VIC 3142",
    type: "House",
    beds: 6,
    baths: 4,
    cars: 3,
    livingSize: 450,
    landSize: 1200,
    houseArea: 450,
    aspect: "North",
    price: 3200000,
    status: "Available",
    listedBy: "David Kim",
    notes: "Magnificent Toorak estate on 1200sqm. Pool, tennis court, self-contained apartment, triple garage.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/8hIjKlMnOpQrStUvWxY" },
      { title: "Contract", url: "https://drive.google.com/drive/folders/8hIjKlMnOpQrStUvWxY" },
      { title: "Authority", url: "https://drive.google.com/drive/folders/8hIjKlMnOpQrStUvWxY" },
    ],
    listingStyle: "Exclusive",
  },
  {
    id: 9,
    category: "Sale",
    title: "Paddington Terrace",
    address: "66 William Street, Paddington NSW 2021",
    type: "House",
    beds: 3,
    baths: 2,
    cars: 1,
    livingSize: 165,
    landSize: 180,
    houseArea: 165,
    aspect: "South",
    price: 2150000,
    status: "Available",
    listedBy: "Sarah Jenkins",
    notes: "Original terrace with contemporary extension. Cast iron lacework, courtyard garden, rooftop terrace.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/9iJkLmNoPqRsTuvWxYz" },
    ],
    listingStyle: "Exclusive",
  },
  {
    id: 10,
    category: "Sale",
    title: "South Yarra One",
    address: "Unit 28, 500 Chapel Street, South Yarra VIC 3141",
    type: "Unit",
    beds: 3,
    baths: 2,
    cars: 2,
    livingSize: 135,
    landSize: null,
    houseArea: 135,
    aspect: "East",
    price: 1850000,
    status: "Hold",
    listedBy: "Michael Chang",
    notes: "Premium apartment overlooking Royal Botanic Gardens. Concierge, gym, pool, private cinema.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/10jKlMnOpQrStUvWxYzA" },
      { title: "Contract", url: "https://drive.google.com/drive/folders/10jKlMnOpQrStUvWxYzA" },
    ],
    listingStyle: "Exclusive",
  },
  {
    id: 11,
    category: "Sale",
    title: "Manly Beach House",
    address: "4 The Corso, Manly NSW 2095",
    type: "House",
    beds: 5,
    baths: 3,
    cars: 2,
    livingSize: 240,
    landSize: 500,
    houseArea: 240,
    aspect: "East",
    price: 2750000,
    status: "Available",
    listedBy: "Emily Rodriguez",
    notes: "Steps to Manly Beach. Dual living, self-contained studio, established gardens, double lock-up garage.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/11kLmNoPqRsTuvWxYzAb" },
    ],
    listingStyle: "Off-Market",
  },
  {
    id: 12,
    category: "Sale",
    title: "Kew Gardens Residence",
    address: "88 Willsmere Road, Kew VIC 3101",
    type: "House",
    beds: 4,
    baths: 3,
    cars: 2,
    livingSize: 260,
    landSize: 720,
    houseArea: 260,
    aspect: "West",
    price: 2980000,
    status: "Available",
    listedBy: "David Kim",
    notes: "Elegant interwar home on prestigious Willsmere Road. Mature gardens, wine cellar, home office.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/12lMnOpQrStUvWxYzAbC" },
      { title: "Contract", url: "https://drive.google.com/drive/folders/12lMnOpQrStUvWxYzAbC" },
    ],
    listingStyle: "Exclusive",
  },
  {
    id: 13,
    category: "Sale",
    title: "Kirribilli Apartment",
    address: "Unit 15, 12 Alfred Street, Kirribilli NSW 2061",
    type: "Apartment",
    beds: 2,
    baths: 1,
    cars: 1,
    livingSize: 78,
    landSize: null,
    houseArea: 78,
    aspect: "North",
    price: 1350000,
    status: "Available",
    listedBy: "Sarah Jenkins",
    notes: "Waterfront apartment with Opera House and Harbour Bridge views. Freshly painted, new carpet.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/13mNopQrStUvWxYzAbCd" },
    ],
    listingStyle: "Off-Market",
  },
  {
    id: 14,
    category: "Sale",
    title: "Brighton Beach Box",
    address: "22 Hampton Street, Brighton VIC 3186",
    type: "House",
    beds: 3,
    baths: 2,
    cars: 1,
    livingSize: 145,
    landSize: 350,
    houseArea: 145,
    aspect: "North",
    price: 2100000,
    status: "Available",
    listedBy: "Michael Chang",
    notes: "Character weatherboard with modern renovation. Walk to Brighton Beach baths, Bay Street shops.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/14nOpQrStUvWxYzAbCdE" },
      { title: "Contract", url: "https://drive.google.com/drive/folders/14nOpQrStUvWxYzAbCdE" },
    ],
    listingStyle: "Exclusive",
  },

  // LEASE LISTINGS (6)
  {
    id: 15,
    category: "Lease",
    title: "CBD Studio",
    address: "Unit 8, 200 Bourke Street, Melbourne VIC 3000",
    type: "Apartment",
    beds: 1,
    baths: 1,
    cars: 0,
    livingSize: 45,
    landSize: null,
    houseArea: 45,
    aspect: "East",
    price: 550,
    status: "Available",
    listedBy: "Emily Rodriguez",
    notes: "Furnished studio in prime CBD location. Gas cooking, secure entry, laundry facilities. Available now.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/15oPqRsTuvWxYzAbCdEf" },
    ],
    listingStyle: "Exclusive",
  },
  {
    id: 16,
    category: "Lease",
    title: "Surry Hills Flat",
    address: "3/45 Crown Street, Surry Hills NSW 2010",
    type: "Apartment",
    beds: 2,
    baths: 1,
    cars: 0,
    livingSize: 70,
    landSize: null,
    houseArea: 70,
    aspect: "North",
    price: 750,
    status: "Available",
    listedBy: "Sarah Jenkins",
    notes: "Light-filled top floor apartment. Original floorboards, gas kitchen, walk to Central Station.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/16pQrStUvWxYzAbCdEfG" },
    ],
    listingStyle: "Off-Market",
  },
  {
    id: 17,
    category: "Lease",
    title: "Richmond Townhouse",
    address: "12 East Street, Richmond VIC 3121",
    type: "House",
    beds: 3,
    baths: 2,
    cars: 1,
    livingSize: 120,
    landSize: null,
    houseArea: 120,
    aspect: "West",
    price: 850,
    status: "Available",
    listedBy: "David Kim",
    notes: "Modern 3-bedroom townhouse with private courtyard. Ducted heating, split system, auto garage.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/17qRsTuvWxYzAbCdEfGh" },
      { title: "Contract", url: "https://drive.google.com/drive/folders/17qRsTuvWxYzAbCdEfGh" },
    ],
    listingStyle: "Exclusive",
  },
  {
    id: 18,
    category: "Lease",
    title: "Double Bay Suite",
    address: "Unit 5, 75 New South Head Road, Double Bay NSW 2028",
    type: "Unit",
    beds: 2,
    baths: 2,
    cars: 1,
    livingSize: 95,
    landSize: null,
    houseArea: 95,
    aspect: "East",
    price: 950,
    status: "Hold",
    listedBy: "Michael Chang",
    notes: "Luxury apartment in exclusive Double Bay. Miele appliances, marble bathrooms, harbour glimpses.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/18rRsTuvWxYzAbCdEfGhI" },
    ],
    listingStyle: "Exclusive",
  },
  {
    id: 19,
    category: "Lease",
    title: "St Kilda Maisonette",
    address: "2/18 Fitzroy Street, St Kilda VIC 3182",
    type: "Apartment",
    beds: 2,
    baths: 1,
    cars: 1,
    livingSize: 80,
    landSize: null,
    houseArea: 80,
    aspect: "South",
    price: 680,
    status: "Available",
    listedBy: "Emily Rodriguez",
    notes: "Charming ground floor apartment. Walk to St Kilda Beach, Luna Park, Acland Street cafes.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/19sTuVwXyZAbCdEfGhIj" },
    ],
    listingStyle: "Off-Market",
  },
  {
    id: 20,
    category: "Lease",
    title: "Neutral Bay Cottage",
    address: "56 Hayes Street, Neutral Bay NSW 2089",
    type: "House",
    beds: 3,
    baths: 2,
    cars: 1,
    livingSize: 110,
    landSize: 200,
    houseArea: 110,
    aspect: "North",
    price: 1250,
    status: "Available",
    listedBy: "David Kim",
    notes: "Renovated cottage with harbour views. North facing, private garden, close to ferry.",
    links: [
      { title: "Floorplan", url: "https://drive.google.com/drive/folders/20tUvWxYzAbCdEfGhIjK" },
      { title: "Contract", url: "https://drive.google.com/drive/folders/20tUvWxYzAbCdEfGhIjK" },
    ],
    listingStyle: "Exclusive",
  },
];

export const colourSchemes = [
  {
    id: "warm-wood",
    name: "Warm Wood",
    description: "Rich timber tones with warm earth accents. Perfect for creating a cosy, inviting atmosphere that connects with nature.",
    colors: ["#8B4513", "#D2691E", "#DEB887", "#F5DEB3", "#FFFAF0"],
  },
  {
    id: "modern-concrete",
    name: "Modern Concrete",
    description: "Sleek industrial palette featuring raw concrete greys and steel accents. Ideal for contemporary urban living spaces.",
    colors: ["#2C3E50", "#5D6D7E", "#ABB2B9", "#E5E8E8", "#F8F9F9"],
  },
  {
    id: "minimalist-white",
    name: "Minimalist White",
    description: "Clean, bright whites with subtle warm undertones. Creates an airy, spacious feeling with timeless elegance.",
    colors: ["#2C3E50", "#7F8C8D", "#ECF0F1", "#FDFEFE", "#FFFFFF"],
  },
  {
    id: "industrial-dark",
    name: "Industrial Dark",
    description: "Bold charcoal and matte black tones with metallic highlights. A dramatic palette for statement interiors.",
    colors: ["#1A1A2E", "#16213E", "#0F3460", "#533483", "#E94560"],
  },
];
